version: "3.8"
services:
    app:
        build:
            args:
                user: admin
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: prueba-back
        container_name: prueba-back
        restart: unless-stopped
        working_dir: /var/www/
        depends_on:
            - mysql
        volumes:
            - ./:/var/www
        networks:
            - prueba-dev

    mysql:
        image: mysql:8.0
        platform: linux/amd64
        container_name: prueba-db
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        ports:
            - "3306:3306"
        volumes:
            - prueba:/var/lib/mysql
        networks:
            - prueba-dev

    nginx:
        image: nginx:alpine
        container_name: prueba-nginx
        restart: unless-stopped
        depends_on:
            - app
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - prueba-dev

volumes:
    prueba:

networks:
    prueba-dev:
        driver: bridge
